import { searchDocuments } from "@/lib/data";
import { getLLMProvider } from "@/lib/providers";
import type { AIEvent, ExecutionResult, RetrievedDocument } from "@/types";

const wait = (ms:number) => new Promise(resolve=>setTimeout(resolve,ms));
const tokenize = (input:string) => input.match(/[A-Za-z]+|[0-9]+|[^\sA-Za-z0-9]/g) || [];
const embed = (input:string) => Array.from({length:12},(_,index)=>Number((((input.charCodeAt(index % Math.max(input.length,1)) || 17) / 255) * 2 - 1).toFixed(4)));
export async function* runRag(prompt:string, mode:"rag"|"direct", executionId:string):AsyncGenerator<AIEvent|{type:"result"; result:ExecutionResult}> {
  const startedAt=Date.now(); const emit=(name:AIEvent["name"],stage:AIEvent["stage"],status:AIEvent["status"],metadata:Record<string,unknown>={}):AIEvent=>({executionId,timestamp:new Date().toISOString(),name,stage,status,metadata});
  yield emit("execution.started","prompt","running",{mode}); yield emit("prompt.received","prompt","completed",{prompt,characters:prompt.length}); await wait(280);
  const tokens=tokenize(prompt); yield emit("tokenization.started","tokens","running",{characters:prompt.length}); await wait(380); yield emit("tokenization.completed","tokens","completed",{tokens,tokenCount:tokens.length,estimated:false});
  let embedding:number[]=[]; let docs:RetrievedDocument[]=[]; let context="";
  if(mode==="rag") { yield emit("agent.started","agent","running"); await wait(220); const shouldRetrieve=!/^what is (25|[0-9]+ ?[+*x-])/.test(prompt.toLowerCase()); yield emit("agent.decision","agent","completed",{retrievalRequired:shouldRetrieve,reason:shouldRetrieve?"Knowledge question benefits from grounding":"Calculation or direct response does not need retrieval"}); if(shouldRetrieve) { yield emit("tool.started","search","running",{tool:"search_knowledge_base",arguments:{query:prompt,topK:5}}); yield emit("embedding.started","embedding","running",{model:process.env.EMBEDDING_MODEL||"mock-embedding-v1"}); await wait(450); embedding=embed(prompt); yield emit("embedding.completed","embedding","completed",{dimensions:embedding.length,preview:embedding.slice(0,4),provider:process.env.OPENAI_API_KEY?"openai":"demo"}); yield emit("tool.completed","search","completed",{tool:"search_knowledge_base",durationMs:450}); yield emit("vector.search.started","search","running",{index:process.env.PINECONE_INDEX||"local-demo-index",namespace:process.env.PINECONE_NAMESPACE||"knowledge-base",topK:5,provider:process.env.PINECONE_API_KEY?"pinecone":"local-demo"}); await wait(520); docs=searchDocuments(prompt); yield emit("vector.search.completed","search","completed",{results:docs.length,scores:docs.map(doc=>doc.score),provider:process.env.PINECONE_API_KEY?"pinecone":"local-demo"}); yield emit("context.started","context","running",{chunks:docs.length}); context=docs.map((doc,index)=>`[${index+1}] ${doc.source}\n${doc.text}`).join("\n\n"); await wait(180); yield emit("context.completed","context","completed",{characters:context.length,chunks:docs.length}); } } else { yield emit("agent.decision","agent","completed",{retrievalRequired:false,reason:"Direct LLM mode selected"}); }
  const provider=getLLMProvider(); yield emit("llm.started","llm","running",{model:provider.model,inputTokens:tokens.length + context.length / 4}); const finalPrompt=`USER PROMPT\\n${prompt}\\n\\nRETRIEVED CONTEXT\\n${context}`; const answer=await provider.generate(finalPrompt); let streamed=""; for await(const part of provider.stream(answer)) { streamed+=part; yield emit("llm.token","llm","running",{token:part}); await wait(24); } yield emit("llm.completed","llm","completed",{outputTokens:tokenize(answer).length}); const completedAt=Date.now(); yield emit("execution.completed","answer","completed",{durationMs:completedAt-startedAt}); yield {type:"result",result:{executionId,answer:streamed.trim(),tokens,tokenCount:tokens.length,embedding,embeddingDimensions:embedding.length,documents:docs,context,model:provider.model,mode,startedAt,completedAt}};
}
